[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = ['MakeTable']

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = ['Template']

# 気になる
# [[plugins]]
# repo = 'mattn/ctrlp-matchfuzzy'
# on_cmd = []

[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = [
    'Files',
    'ProjectFiles',
    'Buffers',
    'BLines',
    'History',
    'Tags',
    'BTags',
    'GFiles',
    'Ag',
	'Helptags',
]
depends = ['fzf']

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_cmd = ['PreviewMarkdown']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_cmd = ['LspInstallServer', 'LspUnInstallServer']
