########## for lsp
# Execute in asynchronous
[[plugins]]
repo = 'prabirshrestha/async.vim'
on_ft = ['python']

# Auto complete
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_ft = ['python']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python']
depends = ['async.vim'] #, 'vim-virtualenv']
hook_source = '''
source ~/Repositories/dotfiles/.vim/vim-lsp.rc.vim
'''

# Add LSP support
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['python']

# [[plugins]]
# repo = 'mattn/vim-lsp-settings'
# on_ft = ['python']
# depends = ['async.vim']

[[pluglins]]
repo = 'w0rp/ale'
on_ft = ['python']
##########


[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = ['MakeTable']

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = ['Template']
