[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = ['MakeTable']

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = ['Template']

# 気になる
# [[plugins]]
# repo = 'mattn/ctrlp-matchfuzzy'
# on_cmd = []
