[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = ['MakeTable']

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = ['Template']

# 気になる
# [[plugins]]
# repo = 'mattn/ctrlp-matchfuzzy'
# on_cmd = []

[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = [
    'Files',
    'ProjectFiles',
    'Buffers',
    'BLines',
    'History',
    'Tags',
    'BTags',
    'GFiles',
    'Ag',
	'Helptags',
]
hook_add = '''
" fzfのリポジトリのパスをランタイムに追加
" なぜかhook_sourceではだめ
set rtp+=~linuxbrew/.linuxbrew/opt/fzf
'''



[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_cmd = ['PreviewMarkdown']
