[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'mattn/vim-maketable'
on_cmd = ['MakeTable']

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = ['Template']
