[[plugins]]
repo = 'Shougo/dein.vim'

########## for lsp
# vim-lspに統合された
# Execute in asynchronous
# [[plugins]]
# repo = 'prabirshrestha/async.vim'

# Auto complete
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

# Auto completion for LSP
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['vim-virtualenv']
# deinがcacheを使ってるからか，実行されないことがあるので.vimrcで実行するようにした
# hook_source = '''
# source ~/Repositories/dotfiles/.vim/vim-lsp.rc.vim
# '''

# [[plugins]]
# repo = 'mattn/vim-lsp-settings'
# depends = ['async.vim']

# lightline は使い続けるか微妙
# LSP-lightline bridge
# [[plugins]]
# repo = 'halkn/lightline-lsp'

# Customize status line
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = '''
#   let g:lightline = {
#   \  'mode_map': {'c': 'NORMAL'},
#   \  'active': {
#   \    'right': [
#   \      [ 'lineinfo' ],
#   \		 [ 'lsp_errors', 'lsp_warnings' ]
#   \    ]
#   \  },
#   \  'component_expand': {
#   \    'lsp_warnings': 'lightline_lsp#warnings',
#   \    'lsp_errors':   'lightline_lsp#errors',
#   \  },
#   \  'component_type': {
#   \    'lsp_warnings': 'warning',
#   \    'lsp_errors':   'errors',
#   \  },
#   \}
# '''
##########

########## colorscheme
# [[plugins]]
# repo = "ulwlu/elly.vim"

[[plugins]]
repo = "morhetz/gruvbox"
##########

[[plugins]]
repo = 'tpope/vim-surround'

# 差分表示
[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "nelstrom/vim-visual-star-search"

# 気になる
# [[plugins]]
# repo = "thinca/vim-quickrun"
